version: '3.5' 

services: 
    angular-service: 
      container_name: angularcontainer  
      build: ./web 
      volumes: 
        - './web:/usr/src/app' 
      ports: 
        - '4200:4200'
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --disable-host-check."


    api:
        build:
          context: .
          dockerfile: Dockerfile
        image: fullstack-challenge-api
        container_name: api
        ports:
          - "8080:8080"
        environment:
          - RDS_HOSTNAME=pdb
          - RDS_PORT=5432
          - RDS_USERNAME=postgres
          - RDS_PASSWORD=admin
          - PROFILE=prod
        expose:
          - 8080
        volumes:
          - ./target:/app